### ISSUE TITLE
Wrong symfony validator namespace is used

### ISSUE THREAD

**Issue by Lexinek** [Kdyby/DoctrineForms#14]
Right after installing DoctrineForms i get this exception:

> Nette\DI\ServiceCreationException
> Service 'doctrineForms.constraintViolationsMapper': Service of type Symfony\Component\Validator\Validator\ValidatorInterface needed by Kdyby\DoctrineForms\ConstraintViolationsMapper::__construct() not found. Did you register it in configuration file?

This can be fixed by editing file Kdyby/DoctrineForms/ConstraintViolationsMapper.php line 21.

Change the use statement from

``` php
use Symfony\Component\Validator\Validator\ValidatorInterface;
```

To

``` php
use Symfony\Component\Validator\ValidatorInterface;
```

Notice there is 2 times \Validator in the namespace (as i checked, this typo is in tests as well and tests will not pass).

**Comment by enumag** [comment]
This can be closed.
