### ISSUE TITLE
Future? Deprecate? New maintainer?

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/DoctrineForms#19]
Let's be honest here. I have no use for this right now and I probably won't have a use for this for at least another year. 

Is there anybody, who wants to take over? We can merge changes from your fork here and you can continue developing it here.

I'll have to deprecate this otherwise.

**Comment by TomasVotruba** [comment]
Ping @enumag and https://github.com/arachne/forms

**Comment by enumag** [comment]
@TomasVotruba Yeah arachne/forms has similar features however it is based on symfony/form, not nette/forms like this library so migrating an existing application to it would be a real pain.

**Comment by TomasVotruba** [comment]
@enumag Allright.

@fprochazka [Deprecated then](https://github.com/DeprecatedPackages).

**Comment by fprochazka** [comment]
This package is deprecated now.

**Comment by TomasVotruba** [comment]
:+1:
