### ISSUE TITLE
Create sandbox with example forms that needs entity mapping

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/DoctrineForms#6]
Use all the relation types
- one to one
- one to many
- many to one
- many to many

With all the variations
- uni-directional
- bi-directional
- self referencing
- relations in containers
- relations in selects, radiolists, checkboxlists, ...
- maping columns with different names to different controls
- ... any other idea?

Create entity model or extend the CMS model in Kdyby\Doctrine Tests (taken from original Doctrine ORM tests).

---

In the first iteration, it should be only "skeleton", no mappings implemented, only plain form definitions and thier rendering (can be used the default or BS3 from nette/forms).

With this kind of application ready, I'll be able to figure out the best API for `Kdyby/DoctrineForms`, implement it and write tests (or we could join our efforts, but let's iterate on it).

---

Also, let's prevent possible conflicts, I've created a repository [fprochazka/kdyby-doctrine-forms-testing-sandbox](https://github.com/fprochazka/kdyby-doctrine-forms-testing-sandbox), that should server this purpose.

If you wanna participate, write that here and I'll give you push rights to that repository. That way we'll know who's working on it and hopefully nobody will do the same work twice.

**Comment by TomasVotruba** [comment]
:+1:
